Sys status message recieved
josezy/tukano pull request #36
Opened 2020-04-16 02:08 UTC by alejonb

SYS_STATUS Message was added from drone messages to get battery status.

2020-04-16 02:51 UTC, josezy requested changes
chimba que le esté metiendo moral 🥳 ahí le dejé algunos comentarios para que organicemos este código bien poderoso 👍

2020-04-16 02:51 UTC, josezy commented on src/actuators.py
> +    def trigget_pin_on(self):
trigget?

2020-04-16 02:51 UTC, josezy commented on src/tukano_service.py
> +        hook = Hook()
esto lo había inicializado arriba porque la idea es tener 1 hook en la applicación, no crear uno cada que llegue este comando

2020-04-16 02:51 UTC, josezy commented on src/tukano_service.py
> +cloud_link = None
```suggestion
cloud_link = create_cloud_link()
```

2020-04-16 02:51 UTC, josezy commented on src/timer.py
> +	timer_names = ['data_collect', 'data_send', 'take_pic']
pase esto en la inicialización del objecto, ver comentario de abajo ⬇️

2020-04-16 02:51 UTC, josezy commented on src/tukano_service.py
> +timer = Timer.Timer()
```suggestion
timer = Timer.Timer(['data_collect', 'data_send', 'take_pic'])
```

2020-04-16 02:51 UTC, josezy commented on src/tukano_service.py
> +        elapsed_times = {tn: now - timer.last_tss[tn] for tn in timer.timer_names}
este calculo debería hacerse internamente en la clase `Timer`

2020-04-16 02:51 UTC, josezy commented on src/tukano_service.py
>          if elapsed_times['data_collect'] > settings.DATA_COLLECT_TIMESPAN:
esta validación también puede meterse dentro de la clase `Timer` y hacer algo como:
`if timer.elapsed('data_collect', settings.DATA_COLLECT_TIMESPAN):`

el `settings.DATA_COLLECT_TIMESPAN` puede hacer parte de la inicialización del timer también

2020-04-17 04:07 UTC, alejonb commented on src/actuators.py
> +    def trigget_pin_on(self):
I was trigger, sorry.

2020-04-17 04:09 UTC, alejonb commented on src/tukano_service.py
> +cloud_link = None
Done

2020-04-18 12:35 UTC, merged